### ISSUE TITLE
npm start error

### ISSUE THREAD

**Issue by mmjd** [denvned/isomorphic-relay-router#2]
starting the todo example raises the following error:

```
d:\git\relay\isomorphic-relay-router\examples\todo>npm start

> @ prestart d:\git\relay\isomorphic-relay-router\examples\todo
> npm run build


> @ build d:\git\relay\isomorphic-relay-router\examples\todo
> npm run update-schema && babel --stage 1 --plugins ./build/babelRelayPlugin src --out-dir lib && webpack


> @ update-schema d:\git\relay\isomorphic-relay-router\examples\todo
> babel-node --optional es7.asyncFunctions ./scripts/updateSchema.js

src\client.js -> lib\client.js
src\components\Todo.js -> lib\components\Todo.js
src\components\TodoApp.js -> lib\components\TodoApp.js
src\components\TodoList.js -> lib\components\TodoList.js
src\components\TodoListFooter.js -> lib\components\TodoListFooter.js
src\components\TodoTextInput.js -> lib\components\TodoTextInput.js
src\data\database.js -> lib\data\database.js
src\data\schema.js -> lib\data\schema.js
src\mutations\AddTodoMutation.js -> lib\mutations\AddTodoMutation.js
src\mutations\ChangeTodoStatusMutation.js -> lib\mutations\ChangeTodoStatusMutation.js
src\mutations\MarkAllTodosMutation.js -> lib\mutations\MarkAllTodosMutation.js
src\mutations\RemoveCompletedTodosMutation.js -> lib\mutations\RemoveCompletedTodosMutation.js
src\mutations\RemoveTodoMutation.js -> lib\mutations\RemoveTodoMutation.js
src\mutations\RenameTodoMutation.js -> lib\mutations\RenameTodoMutation.js
src\queries\ViewerQueries.js -> lib\queries\ViewerQueries.js
src\renderOnServer.js -> lib\renderOnServer.js
src\rootContainerProps.js -> lib\rootContainerProps.js
src\routes.js -> lib\routes.js
src\server.js -> lib\server.js
Hash: 7868205da3073715839c
Version: webpack 1.12.4
Time: 2994ms
 Asset     Size  Chunks             Chunk Names
app.js  1.75 MB       0  [emitted]  main
   [0] ./lib/client.js 1.53 kB {0} [built]
 [570] ./lib/routes.js 1.14 kB {0} [built]
 [572] ./lib/mutations/AddTodoMutation.js 6.8 kB {0} [built]
 [574] ./lib/mutations/RemoveCompletedTodosMutation.js 8.35 kB {0} [built]
 [577] ./lib/mutations/MarkAllTodosMutation.js 7.91 kB {0} [built]
 [579] ./lib/mutations/ChangeTodoStatusMutation.js 7.02 kB {0} [built]
 [580] ./lib/mutations/RemoveTodoMutation.js 6.92 kB {0} [built]
 [581] ./lib/mutations/RenameTodoMutation.js 5.47 kB {0} [built]
 [583] ./lib/queries/ViewerQueries.js 1.31 kB {0} [built]
    + 575 hidden modules

> @ start d:\git\relay\isomorphic-relay-router\examples\todo
> node ./lib/server.js

module.js:338
    throw err;
          ^
Error: Cannot find module './useNodeFetch'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (d:\git\relay\isomorphic-relay-router\examples\todo\lib\renderOnServer.js:11:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\opt\\nodejs\\nodejs-v0.12.4-x64\\\\node.exe" "D:\\opt\\nodejs\\nodejs-v0.12.4-x64\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code ELIFECYCLE
npm ERR! @ start: `node ./lib/server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ start script 'node ./lib/server.js'.
npm ERR! This is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./lib/server.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     d:\git\relay\isomorphic-relay-router\examples\todo\npm-debug.log

d:\git\relay\isomorphic-relay-router\examples\todo>

```

**Comment by denvned** [comment]
Sorry for that. Now it is fixed.
