### ISSUE TITLE
crash on connect

### ISSUE THREAD

**Issue by mmjd** [denvned/isomorphic-relay-router#3]
app crashes after connecting to it with:

```
d:\git\relay\isomorphic-relay-router\examples\todo>npm start

> @ prestart d:\git\relay\isomorphic-relay-router\examples\todo
> npm run build


> @ build d:\git\relay\isomorphic-relay-router\examples\todo
> npm run update-schema && babel --stage 1 --plugins ./build/babelRelayPlugin src --out-dir lib && webpack


> @ update-schema d:\git\relay\isomorphic-relay-router\examples\todo
> babel-node --optional es7.asyncFunctions ./scripts/updateSchema.js

src\client.js -> lib\client.js
src\components\Todo.js -> lib\components\Todo.js
src\components\TodoApp.js -> lib\components\TodoApp.js
src\components\TodoList.js -> lib\components\TodoList.js
src\components\TodoListFooter.js -> lib\components\TodoListFooter.js
src\components\TodoTextInput.js -> lib\components\TodoTextInput.js
src\data\database.js -> lib\data\database.js
src\data\schema.js -> lib\data\schema.js
src\mutations\AddTodoMutation.js -> lib\mutations\AddTodoMutation.js
src\mutations\ChangeTodoStatusMutation.js -> lib\mutations\ChangeTodoStatusMutation.js
src\mutations\MarkAllTodosMutation.js -> lib\mutations\MarkAllTodosMutation.js
src\mutations\RemoveCompletedTodosMutation.js -> lib\mutations\RemoveCompletedTodosMutation.js
src\mutations\RemoveTodoMutation.js -> lib\mutations\RemoveTodoMutation.js
src\mutations\RenameTodoMutation.js -> lib\mutations\RenameTodoMutation.js
src\queries\ViewerQueries.js -> lib\queries\ViewerQueries.js
src\renderOnServer.js -> lib\renderOnServer.js
src\rootContainerProps.js -> lib\rootContainerProps.js
src\routes.js -> lib\routes.js
src\server.js -> lib\server.js
Hash: f75e7d8bb193ddee1462
Version: webpack 1.12.4
Time: 3799ms
 Asset     Size  Chunks             Chunk Names
app.js  1.83 MB       0  [emitted]  main
   [0] ./lib/client.js 1.46 kB {0} [built]
 [669] ./lib/routes.js 1.14 kB {0} [built]
 [671] ./lib/mutations/AddTodoMutation.js 7.88 kB {0} [built]
 [673] ./lib/mutations/RemoveCompletedTodosMutation.js 9.96 kB {0} [built]
 [676] ./lib/mutations/MarkAllTodosMutation.js 9.39 kB {0} [built]
 [678] ./lib/mutations/ChangeTodoStatusMutation.js 8.06 kB {0} [built]
 [679] ./lib/mutations/RemoveTodoMutation.js 7.9 kB {0} [built]
 [680] ./lib/mutations/RenameTodoMutation.js 6.09 kB {0} [built]
 [682] ./lib/queries/ViewerQueries.js 1.37 kB {0} [built]
    + 674 hidden modules

> @ start d:\git\relay\isomorphic-relay-router\examples\todo
> node ./lib/server.js

App is now running on http://localhost:8080
d:\git\relay\isomorphic-relay-router\examples\todo\node_modules\react-relay\node_modules\fbjs\lib\resolveImmediate.js:28
    throw error;
          ^
TypeError: undefined is not a function
    at d:\git\relay\isomorphic-relay-router\examples\todo\node_modules\react-relay\lib\printRelayQueryCall.js:51:18
    at String.replace (native)
    at sanitizeCallValue (d:\git\relay\isomorphic-relay-router\examples\todo\node_modules\react-relay\lib\printRelayQueryCall.js:50:16)
    at printRelayQueryCall (d:\git\relay\isomorphic-relay-router\examples\todo\node_modules\react-relay\lib\printRelayQueryCall.js:31:19)
    at Array.map (native)
    at RelayQueryField.getSerializationKey (d:\git\relay\isomorphic-relay-router\examples\todo\node_modules\react-relay\lib\RelayQuery.js:949:97)
    at RelayQueryField.instrumentedCallback [as getSerializationKey] (d:\git\relay\isomorphic-relay-router\examples\todo\node_modules\react-relay\lib\RelayProfiler.js:129:40)
    at printField (d:\git\relay\isomorphic-relay-router\examples\todo\node_modules\react-relay\lib\printRelayOSSQuery.js:127:31)
    at d:\git\relay\isomorphic-relay-router\examples\todo\node_modules\react-relay\lib\printRelayOSSQuery.js:153:14
    at Array.map (native)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\opt\\nodejs\\nodejs-v0.12.4-x64\\\\node.exe" "D:\\opt\\nodejs\\nodejs-v0.12.4-x64\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code ELIFECYCLE
npm ERR! @ start: `node ./lib/server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ start script 'node ./lib/server.js'.
npm ERR! This is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./lib/server.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     d:\git\relay\isomorphic-relay-router\examples\todo\npm-debug.log

d:\git\relay\isomorphic-relay-router\examples\todo>
```

**Comment by denvned** [comment]
Thank for the report. But I've been unable to reproduce this error... May be, it is because you are using node v0.12, while I've tried node v4 only.

**Comment by denvned** [comment]
You could also try to remove whole project, and install it afresh.

**Comment by denvned** [comment]
I have just released a new version of _isomorphic-relay-router_. Could you please check if the issue is still actual?

**Comment by mmjd** [comment]
the error still happens:

```
App is now running on http://localhost:8080
D:\git\relay\isomorphic-relay-router\examples\todo\node_modules\react-relay\node_modules\fbjs\lib\resolveImmediate.js:28
    throw error;
          ^
TypeError: undefined is not a function
    at D:\git\relay\isomorphic-relay-router\examples\todo\node_modules\react-relay\lib\printRelayQueryCall.js:51:18
    at String.replace (native)
    at sanitizeCallValue (D:\git\relay\isomorphic-relay-router\examples\todo\node_modules\react-relay\lib\printRelayQueryCall.js:50:16)
    at printRelayQueryCall (D:\git\relay\isomorphic-relay-router\examples\todo\node_modules\react-relay\lib\printRelayQueryCall.js:31:19)
    at Array.map (native)
    at RelayQueryField.getSerializationKey (D:\git\relay\isomorphic-relay-router\examples\todo\node_modules\react-relay\lib\RelayQuery.js:949:97)
    at RelayQueryField.instrumentedCallback [as getSerializationKey] (D:\git\relay\isomorphic-relay-router\examples\todo\node_modules\react-relay\lib\RelayProfiler.js:129:40)
    at printField (D:\git\relay\isomorphic-relay-router\examples\todo\node_modules\react-relay\lib\printRelayOSSQuery.js:127:31)
    at D:\git\relay\isomorphic-relay-router\examples\todo\node_modules\react-relay\lib\printRelayOSSQuery.js:153:14
    at Array.map (native)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\opt\\nodejs\\nodejs-v0.12.4-x64\\\\node.exe" "D:\\opt\\nodejs\\nodejs-v0.12.4-x64\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code ELIFECYCLE
npm ERR! @ start: `node ./lib/server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ start script 'node ./lib/server.js'.
npm ERR! This is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./lib/server.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\git\relay\isomorphic-relay-router\examples\todo\npm-debug.log
```

**Comment by denvned** [comment]
I've found the cause of the problem. Relay uses `String.prototype.repeat` inside `printRelayQueryCall`, and Node.js v0.12 doesn't support that by default.

So, you have either to update Node.js to v4, or to start server with `--harmony` flag: `node --harmony ./lib/server.js`

**Comment by mmjd** [comment]
thank you. it worked with --harmony but no style comes with the page. could you help please?

**Comment by mmjd** [comment]
todo example works without any problem. thank you for you help.

**Comment by denvned** [comment]
> but no style comes with the page. could you help please?

The styles are now fixed: https://github.com/denvned/isomorphic-relay-router/commit/c992bcd3773ba23008df1ec5585ac094b0eb2013 It looks much nicer now :smile:
