### ISSUE TITLE
Error: No result for query "$$_route[1]_question"

### ISSUE THREAD

**Issue by filod** [denvned/isomorphic-relay-router#4]
```
Error: No result for query "$$_route[1]_question"
    at /Users/filod/shen/gs/node_modules/isomorphic-relay/lib/loadAndStoreData.js:50:27
    at Array.forEach (native)
    at getQueryResults (/Users/filod/shen/gs/node_modules/isomorphic-relay/lib/loadAndStoreData.js:47:36)
    at /Users/filod/shen/gs/node_modules/isomorphic-relay/lib/loadAndStoreData.js:40:25
    at /Users/filod/shen/gs/node_modules/react-relay/lib/GraphQLQueryRunner.js:169:7
    at tryCallOne (/Users/filod/shen/gs/node_modules/react-relay/node_modules/fbjs/node_modules/promise/lib/core.js:37:12)
    at /Users/filod/shen/gs/node_modules/react-relay/node_modules/fbjs/node_modules/promise/lib/core.js:103:15
    at flush (/Users/filod/shen/gs/node_modules/asap/raw.js:50:29)
    at doNTCallback0 (node.js:428:9)
    at process._tickCallback (node.js:357:13)
```

i got this only when i refresh page (repeat & quick), seems the relay context issue ?

https://github.com/facebook/relay/issues/558

**Comment by denvned** [comment]
Thanks for the report. This should be fixed now, please tell if it's not.

**Comment by filod** [comment]
Great job !
