### ISSUE TITLE
React can't find the root component node for data-reactid...

### ISSUE THREAD

**Issue by filod** [denvned/isomorphic-relay-router#5]
```
Warning: React can't find the root component node for data-reactid value `.mnt2f73o5c.0.0.0.$-1`. If you're seeing this message, it probably means that you've loaded two copies of React on the page. At this time, only a single copy of React can be loaded at a time.
TypeError: Cannot read property 'firstChild' of undefined
    at Object.ReactMount.findComponentRoot (webpack:///./~/react/lib/ReactMount.js?:715:39)
    at Object.ReactMount.findReactNodeByID (webpack:///./~/react/lib/ReactMount.js?:679:23)
    at Object.getNode (webpack:///./~/react/lib/ReactMount.js?:162:32)
    at Object.SimpleEventPlugin.didPutListener (webpack:///./~/react/lib/SimpleEventPlugin.js?:571:29)
    at Object.EventPluginHub.putListener (webpack:///./~/react/lib/EventPluginHub.js?:153:20)
    at Object.wrapper [as putListener] (webpack:///./~/react/lib/ReactPerf.js?:66:21)
    at Object.putListener (webpack:///./~/react/lib/ReactDOMComponent.js?:234:28)
    at CallbackQueue.assign.notifyAll (webpack:///./~/react/lib/CallbackQueue.js?:65:22)
    at ReactReconcileTransaction.ON_DOM_READY_QUEUEING.close (webpack:///./~/react/lib/ReactReconcileTransaction.js?:81:26)
    at ReactReconcileTransaction.Mixin.closeAll (webpack:///./~/react/lib/Transaction.js?:202:25)
    at ReactReconcileTransaction.Mixin.perform (webpack:///./~/react/lib/Transaction.js?:149:16)
    at ReactUpdatesFlushTransaction.Mixin.perform (webpack:///./~/react/lib/Transaction.js?:136:20)
    at ReactUpdatesFlushTransaction.assign.perform (webpack:///./~/react/lib/ReactUpdates.js?:86:38)
    at Object.flushBatchedUpdates (webpack:///./~/react/lib/ReactUpdates.js?:147:19)
    at Object.wrapper [as flushBatchedUpdates] (webpack:///./~/react/lib/ReactPerf.js?:66:21)
    at ReactDefaultBatchingStrategyTransaction.Mixin.closeAll (webpack:///./~/react/lib/Transaction.js?:202:25)
    at ReactDefaultBatchingStrategyTransaction.Mixin.perform (webpack:///./~/react/lib/Transaction.js?:149:16)
    at Object.ReactDefaultBatchingStrategy.batchedUpdates (webpack:///./~/react/lib/ReactDefaultBatchingStrategy.js?:62:19)
    at Object.enqueueUpdate (webpack:///./~/react/lib/ReactUpdates.js?:176:22)
    at enqueueUpdate (webpack:///./~/react/lib/ReactUpdateQueue.js?:24:16)
    at Object.ReactUpdateQueue.enqueueSetState (webpack:///./~/react/lib/ReactUpdateQueue.js?:190:5)
    at RelayContainer.ReactComponent.setState (/Users/filod/shen/gs/node_modules/react/lib/ReactComponent.js:65:16)
    at RelayContainer._handleFragmentDataUpdate (/Users/filod/shen/gs/node_modules/react-relay/lib/RelayContainer.js:446:12)
    at GraphQLStoreSingleQueryResolver._handleChange (/Users/filod/shen/gs/node_modules/react-relay/lib/GraphQLStoreQueryResolver.js:243:12)
    at Object.ErrorUtils.applyWithGuard (/Users/filod/shen/gs/node_modules/react-relay/node_modules/fbjs/lib/ErrorUtils.js:18:21)
    at processSubscriber (/Users/filod/shen/gs/node_modules/react-relay/lib/GraphQLStoreChangeEmitter.js:100:20)
    at Array.forEach (native)
    at processSubscribers (/Users/filod/shen/gs/node_modules/react-relay/lib/GraphQLStoreChangeEmitter.js:85:15)
    at ReactDefaultBatchingStrategyTransaction.Mixin.perform (/Users/filod/shen/gs/node_modules/react/lib/Transaction.js:136:20)
    at Object.ReactDefaultBatchingStrategy.batchedUpdates (/Users/filod/shen/gs/node_modules/react/lib/ReactDefaultBatchingStrategy.js:62:19)
    at batchedUpdates (/Users/filod/shen/gs/node_modules/react/lib/ReactUpdates.js:94:20)
    at processBroadcasts (/Users/filod/shen/gs/node_modules/react-relay/lib/GraphQLStoreChangeEmitter.js:80:5)
    at tryCallOne (/Users/filod/shen/gs/node_modules/react-relay/node_modules/fbjs/node_modules/promise/lib/core.js:37:12)
    at /Users/filod/shen/gs/node_modules/react-relay/node_modules/fbjs/node_modules/promise/lib/core.js:103:15
    at flush (/Users/filod/shen/gs/node_modules/asap/raw.js:50:29)
    at doNTCallback0 (node.js:408:9)
    at process._tickCallback (node.js:337:13)
```

the error happen in the second page refresh (everything is fine in first access of page), I can not figure out why this happen, the only differences from my code to todomvc example is *_i use webpack to build server-side code *_

besides, if i change code from:

```
class X extends React.Component {
  handleClick(){}
  render(){
    return <div onClick={this.handleClick.bind(this)}></div>
  }
}
```

to

```
class X extends React.Component {
  handleClick = () => {}
  render(){
    return <div onClick={this.handleClick}></div>
  }
}
```

The error would be gone.

Did I miss something or this may have issue with webpack ?

or this is the bug related to react: https://github.com/facebook/react/issues/5383

**Comment by denvned** [comment]
Yeah, I have seen this error many times while was developing isomorphic-relay-router. It boils down to React DOM updates on the server after it have been already rendered and unmounted. Usually, that happens because some component subscribed to something asynchronous, e.g. to updates to the Relay store.

That's why you need to inject no-on batching strategy on the server (only):

``` javascript
GraphQLStoreChangeEmitter.injectBatchingStrategy(() => {});
```

Also make sure your React components don't perform any asynchronous operations, and don't subscribe to anything in the `constructor`, in `componentWillMount`, or in `render`, which are invoked on the server. Do it in `componentDidMount` if needed (this method is not invoked on the server).

**Comment by filod** [comment]
it's hard to touch third party lib like `react-router`'s `Link` component.
(but it's ok to use `Link` in non-route-component)

**Comment by denvned** [comment]
So, you have injected the batching strategy, and still get that error? Injecting that helped me with `Link`s before.

P.S.
See a demonstration of the general problem: http://codepen.io/dened/pen/YyByYr

**Comment by denvned** [comment]
I've opened https://github.com/facebook/react/issues/5473

**Comment by filod** [comment]
Yep, still get that error **(only happens in route-component which is also wrapped by relay container )**

**Comment by denvned** [comment]
Your stack trace suggests that [this code](https://github.com/facebook/relay/blob/v0.5.0/src/container/RelayContainer.js#L77-L79) overrides your batching strategy. So, just make sure you inject the batching strategy **after** _"react-relay"_ module was already loaded.

**Comment by filod** [comment]
sure, but it does work for me...(even if i remove `GraphQLStoreChangeEmitter.injectBatchingStrategy(ReactDOM.unstable_batchedUpdates)`)

---

I know why this happen,  webpack resolve `GraphQLStoreChangeEmitter` and `react-relay/lib/GraphQLStoreChangeEmitter` as two different modules.

**Comment by denvned** [comment]
> I know why this happen, webpack resolve GraphQLStoreChangeEmitter and react-relay/lib/GraphQLStoreChangeEmitter as two different modules.

Probably, you have two copies of _react-relay_ in your node modules tree.

**Comment by filod** [comment]
just make node_modules as external for backend could solve this.
see: https://github.com/jlongster/backend-with-webpack/blob/part1/webpack.config.js#L21

and remember to add specifc deps:

```
nodeModules.push({
  'react-relay/lib/GraphQLStoreChangeEmitter': 'commonjs react-relay/lib/GraphQLStoreChangeEmitter'
})
...
import GraphQLStoreChangeEmitter from 'react-relay/lib/GraphQLStoreChangeEmitter'
```

**Comment by denvned** [comment]
> and remember to add specifc deps:

Or you can just specify all non-relative module paths as external:

```
...
target: 'node',
output: {
    path: path.resolve(__dirname, 'lib'),
    filename: 'server.js',
    libraryTarget: 'commonjs2'
},
externals: /^[^.]/,
...
```

**Comment by dannypk** [comment]
@denvned Thank you for this part "don't subscribe to anything in the constructor, in componentWillMount, or in render". That solved my problem, i had a Promise.all in componentWillMount and was getting this annoying warning message. Moved it to componentDidMount and no more warnings. Thanks!

**Comment by ffs889** [comment]
Thought I'd leave this here just in case:

I ran into the same issue as filod, but with a ridiculously simple and overlooked explanation: I had a debug line on the client calling renderToString (react-dom/server) to debug prior rendering issues, in addition to rendering the actual DOM. I suppose this caused the application to execute twice, causing a whole range of issues. Mind you, one probably shouldn't be calling renderToString on the client in the first place!
